import React from 'react'
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

export const metadata = {
  title: "home page",
  description: "Generated by create next app",
};

const layout = ({children}) => {
  return (
    <>
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
    </>
  )
}

export default layout